services:

  demo_tech:
    container_name: demo_tech
    image: demo_tech
    env_file:
      - .env
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "${DEMO_TECH_OUTER_PORT}:${DEMO_TECH_INNER_PORT}"
    volumes:
      - ../logs:/app/logs
    networks:
      - demo_tech_network
    depends_on:
      - demo_tech_postgres

  demo_tech_postgres:
    container_name: demo_tech_postgres
    image: postgres:16.3-alpine3.19
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../logs:/app/logs
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - demo_tech_network

volumes:
  postgres_data:

networks:
  demo_tech_network:
    name: demo_tech_network
    external: true
